import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

const imagePaths = {
  dog: '/images/mock_dog_1775037305181.png',
  dogAlt: '/images/mock_dog_alt.svg',
  cat: '/images/mock_cat_1775037291038.png',
  catAlt: '/images/mock_cat_alt.svg',
  bird: '/images/mock_bird_1775037276059.png',
  birdAlt: '/images/mock_bird_alt.svg',
  rabbit: '/images/mock_rabbit.svg',
  rabbitAlt: '/images/mock_rabbit_alt.svg',
  livestock: '/images/mock_livestock.svg',
  livestockAlt: '/images/mock_livestock_alt.svg',
  supplies: '/images/mock_supplies.svg',
  suppliesAlt: '/images/mock_supplies_alt.svg',
};

const imagePools = {
  dog: [imagePaths.dog, imagePaths.dogAlt],
  cat: [imagePaths.cat, imagePaths.catAlt],
  bird: [imagePaths.bird, imagePaths.birdAlt],
  rabbit: [imagePaths.rabbit, imagePaths.rabbitAlt],
  livestock: [imagePaths.livestock, imagePaths.livestockAlt],
  supplies: [imagePaths.supplies, imagePaths.suppliesAlt],
};

const daysFromNow = (days) => new Date(Date.now() + days * 24 * 60 * 60 * 1000);

const buildDescription = ({ lead, details, fit }) => [lead, details, fit].join(' ');

const escapeXml = (value) => String(value)
  .replaceAll('&', '&amp;')
  .replaceAll('<', '&lt;')
  .replaceAll('>', '&gt;')
  .replaceAll('"', '&quot;')
  .replaceAll("'", '&apos;');

const hashString = (value) => {
  let hash = 0;
  for (let i = 0; i < value.length; i += 1) {
    hash = (hash * 31 + value.charCodeAt(i)) >>> 0;
  }
  return hash;
};

const getImagePoolKey = (item) => {
  if (item.category === 'livestock') return 'livestock';
  if (item.category === 'supplies') return 'supplies';
  if (item.species === 'Dog') return 'dog';
  if (item.species === 'Cat') return 'cat';
  if (item.species === 'Bird') return 'bird';
  if (item.species === 'Rabbit') return 'rabbit';
  if (item.species === 'Cattle' || item.species === 'Goat' || item.species === 'Sheep' || item.species === 'Swine') return 'livestock';
  return 'supplies';
};

const makeImageDataUrl = (item, index, variant = 0) => {
  const pool = imagePools[getImagePoolKey(item)] || [imagePaths.supplies];
  const baseKey = getImagePoolKey(item);
  const base = pool[(index + variant) % pool.length];
  const hash = hashString(`${item.title}|${item.petName}|${item.breed}|${index}|${variant}`);
  const accent = ['#D97706', '#0EA5E9', '#10B981', '#8B5CF6', '#E11D48'][hash % 5];
  const accent2 = ['#F59E0B', '#38BDF8', '#34D399', '#A78BFA', '#FB7185'][(hash >> 3) % 5];
  const categoryLabel = {
    dog: 'DOG',
    cat: 'CAT',
    bird: 'BIRD',
    rabbit: 'RABBIT',
    livestock: 'FARM',
    supplies: 'SUPPLY',
  }[baseKey] || 'REHOME';
  const headline = escapeXml(item.petName || item.title);
  const subline = escapeXml(item.breed || item.species || 'Marketplace');
  const footer = escapeXml(item.location || 'Marketplace');
  const svg = `
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 600" role="img" aria-label="${headline}">
      <defs>
        <linearGradient id="bg" x1="0" x2="1" y1="0" y2="1">
          <stop offset="0%" stop-color="${accent}" />
          <stop offset="100%" stop-color="${accent2}" />
        </linearGradient>
      </defs>
      <rect width="800" height="600" rx="40" fill="url(#bg)" />
      <image href="${base}" x="24" y="24" width="752" height="360" preserveAspectRatio="xMidYMid slice" opacity="0.92" />
      <rect x="42" y="382" width="716" height="176" rx="28" fill="#08101C" fill-opacity="0.82" />
      <text x="64" y="444" font-size="46" font-family="Arial, Helvetica, sans-serif" font-weight="700" fill="#FFFFFF">${headline}</text>
      <text x="64" y="490" font-size="28" font-family="Arial, Helvetica, sans-serif" fill="#E5E7EB">${subline}</text>
      <text x="64" y="534" font-size="22" font-family="Arial, Helvetica, sans-serif" fill="#FDE68A">${categoryLabel}</text>
      <text x="590" y="534" font-size="22" font-family="Arial, Helvetica, sans-serif" fill="#E5E7EB" text-anchor="end">${footer}</text>
    </svg>`;
  return `data:image/svg+xml;charset=UTF-8,${encodeURIComponent(svg)}`;
};

const buildImages = (item, index) => [
  makeImageDataUrl(item, index, 0),
  makeImageDataUrl(item, index, 1),
];

const buildAuctionMeta = (price, index) => ({
  reservePrice: Math.round(price * 0.9),
  currentBid: Math.round(price * 0.95),
  bidCount: 2 + (index % 7),
  auctionEndsAt: daysFromNow(4 + (index % 8)),
});

const buildListing = (item, userId, index) => {
  const isAuction = item.listingType === 'auction';
  const auctionMeta = isAuction ? buildAuctionMeta(item.price, index) : {};

  return {
    title: item.title,
    petName: item.petName,
    species: item.species,
    breed: item.breed,
    age: item.age,
    gender: item.gender,
    size: item.size,
    description: buildDescription(item),
    price: item.price,
    status: item.status || 'available',
    images: JSON.stringify(buildImages(item, index)),
    location: item.location,
    vaccinated: item.vaccinated ?? false,
    neutered: item.neutered ?? false,
    category: item.category,
    listingType: item.listingType || 'fixed',
    lotSize: item.lotSize ?? 1,
    allowPartialSale: item.allowPartialSale ?? true,
    ...auctionMeta,
    userId,
  };
};

const ensureUser = async ({ email, passwordHash, resetPassword = false, ...profile }) => {
  const existing = await prisma.user.findUnique({ where: { email } });

  if (existing) {
    const updateData = {
      name: profile.name,
      location: profile.location,
      bio: profile.bio,
      isVerifiedBreeder: profile.isVerifiedBreeder,
    };

    if (resetPassword) {
      updateData.password = passwordHash;
    }

    return prisma.user.update({
      where: { id: existing.id },
      data: updateData,
    });
  }

  return prisma.user.create({
    data: {
      ...profile,
      email,
      password: passwordHash,
    },
  });
};

const syncListing = async (item, userId, index) => {
  const data = buildListing(item, userId, index);
  const existingListings = await prisma.listing.findMany({
    where: { userId, title: item.title },
    orderBy: { createdAt: 'asc' },
  });

  if (existingListings.length > 0) {
    const [existing, ...duplicates] = existingListings;

    if (duplicates.length > 0) {
      await prisma.listing.deleteMany({
        where: { id: { in: duplicates.map((listing) => listing.id) } },
      });
    }

    const listing = await prisma.listing.update({
      where: { id: existing.id },
      data,
    });
    return { listing, action: duplicates.length > 0 ? 'deduped' : 'updated' };
  }

  const listing = await prisma.listing.create({ data });
  return { listing, action: 'created' };
};

const ensureReview = async (data) => {
  const existing = await prisma.review.findFirst({
    where: {
      reviewerId: data.reviewerId,
      sellerId: data.sellerId,
      comment: data.comment ?? null,
    },
  });

  if (existing) {
    return prisma.review.update({
      where: { id: existing.id },
      data: {
        rating: data.rating,
        comment: data.comment ?? null,
      },
    });
  }

  return prisma.review.create({ data });
};

const ensureMessage = async (data) => {
  const existing = await prisma.message.findFirst({
    where: {
      senderId: data.senderId,
      receiverId: data.receiverId,
      listingId: data.listingId,
      content: data.content ?? null,
    },
  });

  if (existing) {
    return existing;
  }

  return prisma.message.create({ data });
};

const ensureFavorite = async (userId, listingId) => prisma.favorite.upsert({
  where: {
    userId_listingId: { userId, listingId },
  },
  update: {},
  create: { userId, listingId },
});

async function seed() {
  console.log('Syncing demo marketplace catalog without deleting existing data...');

  const passwordHash = await bcrypt.hash('password123', 12);

  const [sarah, james, maria, admin] = await Promise.all([
    ensureUser({
      name: 'Sarah Mitchell',
      email: 'sarah@example.com',
      passwordHash,
      resetPassword: true,
      location: 'Austin, TX',
      bio: 'Family-first breeder focused on dogs, barnyard starters, and well-socialized young animals.',
      isVerifiedBreeder: true,
    }),
    ensureUser({
      name: 'James Cooper',
      email: 'james@example.com',
      passwordHash,
      resetPassword: true,
      location: 'Seattle, WA',
      bio: 'Practical homestead seller with a soft spot for cats, rabbits, and small-farm animals.',
      isVerifiedBreeder: true,
    }),
    ensureUser({
      name: 'Maria Santos',
      email: 'maria@example.com',
      passwordHash,
      resetPassword: true,
      location: 'Miami, FL',
      bio: 'Livestock and farm-supply specialist with a clean, steady inventory of larger animals and gear.',
      isVerifiedBreeder: true,
    }),
    ensureUser({
      name: 'Admin',
      email: 'admin@rehome.world',
      passwordHash,
      resetPassword: false,
      location: 'New York, NY',
      bio: 'Rehome Marketplace Administrator',
      isVerifiedBreeder: true,
    }),
  ]);

  const sarahItems = [
    {
      title: 'Sunny - Golden Retriever Companion',
      petName: 'Sunny',
      species: 'Dog',
      breed: 'Golden Retriever',
      age: '4 Months',
      gender: 'Male',
      size: 'Large',
      price: 950,
      location: 'Austin, TX',
      category: 'pets',
      listingType: 'fixed',
      vaccinated: true,
      neutered: false,
      images: [imagePaths.dog],
      lead: 'Sunny is a cheerful Golden Retriever puppy with a soft coat and a very people-focused personality.',
      details: 'He is vaccinated, vet-checked, and already comfortable with crate time, leash walks, and gentle play sessions.',
      fit: 'A strong fit for a family that wants an eager trainer and a mellow dog once the day winds down.',
    },
    {
      title: 'Maggie - Labrador Retriever',
      petName: 'Maggie',
      species: 'Dog',
      breed: 'Labrador Retriever',
      age: '10 Months',
      gender: 'Female',
      size: 'Large',
      price: 1100,
      location: 'Dallas, TX',
      category: 'pets',
      listingType: 'fixed',
      vaccinated: true,
      neutered: true,
      images: [imagePaths.dog],
      lead: 'Maggie is a sturdy young Lab with an easy grin, strong recall, and a calm way of settling around the house.',
      details: 'She is house trained, vaccinated, and used to children, food bowls, and a busy household rhythm.',
      fit: 'Best for an active home that wants a dependable dog for errands, fetch, and weekend walks.',
    },
    {
      title: 'Roscoe - Miniature Poodle',
      petName: 'Roscoe',
      species: 'Dog',
      breed: 'Miniature Poodle',
      age: '2 Years',
      gender: 'Male',
      size: 'Small',
      price: 1250,
      location: 'San Antonio, TX',
      category: 'pets',
      listingType: 'fixed',
      vaccinated: true,
      neutered: true,
      images: [imagePaths.dog],
      lead: 'Roscoe is a bright Miniature Poodle with a tidy coat and a confident, quick-learning temperament.',
      details: 'He is neutered, current on vaccinations, and already comfortable with grooming, car rides, and apartment living.',
      fit: 'A practical pick for someone who wants a compact dog with brains, routine, and low shedding.',
    },
    {
      title: 'Daisy - Beagle',
      petName: 'Daisy',
      species: 'Dog',
      breed: 'Beagle',
      age: '8 Months',
      gender: 'Female',
      size: 'Medium',
      price: 780,
      location: 'Baton Rouge, LA',
      category: 'pets',
      listingType: 'fixed',
      vaccinated: true,
      neutered: false,
      images: [imagePaths.dog],
      lead: 'Daisy is a curious Beagle pup with a happy nose, a friendly tail, and plenty of puppy enthusiasm.',
      details: 'She is vaccinated, healthy, and being raised with a clean routine, crate time, and basic leash manners.',
      fit: 'Best for a family that wants a vocal, affectionate companion with classic hound personality.',
    },
    {
      title: 'Porter - Australian Shepherd',
      petName: 'Porter',
      species: 'Dog',
      breed: 'Australian Shepherd',
      age: '14 Months',
      gender: 'Male',
      size: 'Medium',
      price: 1400,
      location: 'Boise, ID',
      category: 'pets',
      listingType: 'fixed',
      vaccinated: true,
      neutered: true,
      images: [imagePaths.dog],
      lead: 'Porter is an alert Aussie with quick feet, strong herding instincts, and an easy bond with one handler.',
      details: 'He is vaccinated, neutered, and used to structured play, trail walks, and positive training sessions.',
      fit: 'A good choice for an owner who wants a smart working dog with a lot of drive and loyalty.',
    },
    {
      title: 'Clover - Cocker Spaniel',
      petName: 'Clover',
      species: 'Dog',
      breed: 'Cocker Spaniel',
      age: '3 Years',
      gender: 'Female',
      size: 'Medium',
      price: 860,
      location: 'Nashville, TN',
      category: 'pets',
      listingType: 'fixed',
      status: 'pending',
      vaccinated: true,
      neutered: true,
      images: [imagePaths.dog],
      lead: 'Clover is a soft-eared Cocker Spaniel with a calm indoor manner and a steady love of being near her people.',
      details: 'She is vaccinated, house trained, and already comfortable with brushing, car rides, and quiet evenings.',
      fit: 'A nice fit for a home looking for a lower-key dog with a warm, affectionate personality.',
    },
    {
      title: 'Juniper - Ragdoll',
      petName: 'Juniper',
      species: 'Cat',
      breed: 'Ragdoll',
      age: '16 Months',
      gender: 'Female',
      size: 'Medium',
      price: 975,
      location: 'Portland, OR',
      category: 'pets',
      listingType: 'fixed',
      vaccinated: true,
      neutered: true,
      images: [imagePaths.cat],
      lead: 'Juniper is a silky Ragdoll with a relaxed cuddle style and a habit of following people from room to room.',
      details: 'She is litter trained, spayed, vaccinated, and comfortable with respectful dogs and a quiet household.',
      fit: 'Best for an adopter who wants a gentle lap cat and does not mind a little daily brushing.',
    },
    {
      title: 'Theo - British Shorthair',
      petName: 'Theo',
      species: 'Cat',
      breed: 'British Shorthair',
      age: '2 Years',
      gender: 'Male',
      size: 'Medium',
      price: 1125,
      location: 'Minneapolis, MN',
      category: 'pets',
      listingType: 'fixed',
      vaccinated: true,
      neutered: true,
      images: [imagePaths.cat],
      lead: 'Theo is a plush British Shorthair with a calm stare, a round face, and a very steady indoor temperament.',
      details: 'He is neutered, vaccinated, and used to being handled, brushed, and fed on a predictable routine.',
      fit: 'A strong fit for apartments, first-time cat owners, and anyone who prefers a composed companion.',
    },
    {
      title: 'Miso - Domestic Shorthair',
      petName: 'Miso',
      species: 'Cat',
      breed: 'Domestic Shorthair',
      age: '4 Years',
      gender: 'Male',
      size: 'Medium',
      price: 260,
      location: 'Salt Lake City, UT',
      category: 'pets',
      listingType: 'fixed',
      vaccinated: true,
      neutered: true,
      images: [imagePaths.cat],
      lead: 'Miso is a relaxed, good-natured house cat with a low-drama personality and a soft affection for laps.',
      details: 'He is fixed, vaccinated, litter trained, and happiest with a clean feeding routine and a sunny window.',
      fit: 'A budget-friendly companion for someone who wants an easy indoor cat without extra fuss.',
    },
    {
      title: 'Pixel - Siamese',
      petName: 'Pixel',
      species: 'Cat',
      breed: 'Siamese',
      age: '11 Months',
      gender: 'Female',
      size: 'Small',
      price: 1320,
      location: 'Austin, TX',
      category: 'pets',
      listingType: 'fixed',
      status: 'sold',
      vaccinated: true,
      neutered: false,
      images: [imagePaths.cat],
      lead: 'Pixel is a talkative Siamese kitten with sharp blue eyes, a playful streak, and a strong bond to people.',
      details: 'She is vaccinated, healthy, and already comfortable with feather toys, scratching posts, and short grooming sessions.',
      fit: 'Best for a home that wants a lively cat who will stay involved in the daily routine.',
    },
    {
      title: 'Honey - Maine Coon',
      petName: 'Honey',
      species: 'Cat',
      breed: 'Maine Coon',
      age: '7 Months',
      gender: 'Female',
      size: 'Large',
      price: 1485,
      location: 'Charleston, SC',
      category: 'pets',
      listingType: 'fixed',
      vaccinated: true,
      neutered: false,
      images: [imagePaths.cat],
      lead: 'Honey is a fluffy Maine Coon kitten with a huge frame, a playful attitude, and a very soft meow.',
      details: 'She is vet-checked, vaccinated, and already getting used to brushes, climbing shelves, and calm handling.',
      fit: 'A great match for a home that wants a social cat with room to grow into a gentle giant.',
    },
    {
      title: 'Maple - Tabby Mix',
      petName: 'Maple',
      species: 'Cat',
      breed: 'Tabby Mix',
      age: '3 Years',
      gender: 'Female',
      size: 'Medium',
      price: 315,
      location: 'Kansas City, MO',
      category: 'pets',
      listingType: 'fixed',
      vaccinated: true,
      neutered: true,
      images: [imagePaths.cat],
      lead: 'Maple is a steady tabby with a friendly face, a warm lap-cat habit, and a patient way with visitors.',
      details: 'She is spayed, vaccinated, and used to a clean litter setup and a predictable feeding schedule.',
      fit: 'A good fit for a home that wants a dependable cat with a calm, easygoing temperament.',
    },
    {
      title: 'Tilly - Rabbit Companion',
      petName: 'Tilly',
      species: 'Rabbit',
      breed: 'Holland Lop',
      age: '9 Months',
      gender: 'Female',
      size: 'Small',
      price: 210,
      location: 'Seattle, WA',
      category: 'pets',
      listingType: 'fixed',
      vaccinated: false,
      neutered: false,
      images: [imagePaths.rabbit],
      lead: 'Tilly is a sweet Holland Lop with velvety ears and a habit of settling down once she trusts her people.',
      details: 'She is litter box trained, healthy, and being handled daily so she stays calm with brushing and feeding time.',
      fit: 'A nice choice for an adopter who wants a quiet indoor rabbit and already has a proper enclosure ready.',
    },
    {
      title: 'Basil - Mini Rex',
      petName: 'Basil',
      species: 'Rabbit',
      breed: 'Mini Rex',
      age: '1 Year',
      gender: 'Male',
      size: 'Small',
      price: 180,
      location: 'Madison, WI',
      category: 'pets',
      listingType: 'fixed',
      vaccinated: false,
      neutered: true,
      images: [imagePaths.rabbit],
      lead: 'Basil is a compact Mini Rex with a velvety coat and a curious nose that wants to inspect everything.',
      details: 'He is calm around hands, used to hay-based feeding, and already comfortable with a tidy indoor setup.',
      fit: 'Best for a family that wants a low-noise pet with a lot of character in a small package.',
    },
    {
      title: 'Poppy - Angora Bunny',
      petName: 'Poppy',
      species: 'Rabbit',
      breed: 'Angora',
      age: '10 Months',
      gender: 'Female',
      size: 'Small',
      price: 235,
      location: 'Bozeman, MT',
      category: 'pets',
      listingType: 'fixed',
      vaccinated: false,
      neutered: false,
      images: [imagePaths.rabbit],
      lead: 'Poppy is a fluffy Angora bunny with a soft coat, gentle eyes, and a quiet, easygoing temperament.',
      details: 'She is handled often, used to grooming, and needs a home ready for regular coat care and an exercise pen.',
      fit: 'A strong fit for someone who wants a beautiful rabbit and is comfortable with weekly upkeep.',
    },
    {
      title: 'Bluebell - Parakeet Pair',
      petName: 'Bluebell',
      species: 'Bird',
      breed: 'Budgerigar Pair',
      age: '8 Months',
      gender: 'Pair',
      size: 'Small',
      price: 190,
      location: 'Tampa, FL',
      category: 'pets',
      listingType: 'fixed',
      status: 'pending',
      vaccinated: false,
      neutered: false,
      images: [imagePaths.bird],
      lead: 'Bluebell is a bonded pair of bright parakeets with a cheerful chatter and an easy, homey presence.',
      details: 'They are healthy, used to a routine feeding schedule, and accustomed to a covered cage with daily attention.',
      fit: 'Best for a home that wants a small, lively pet bird with a steady soundtrack.',
    },
    {
      title: 'Cedar - Cockatiel',
      petName: 'Cedar',
      species: 'Bird',
      breed: 'Cockatiel',
      age: '2 Years',
      gender: 'Male',
      size: 'Small',
      price: 420,
      location: 'Phoenix, AZ',
      category: 'pets',
      listingType: 'fixed',
      vaccinated: false,
      neutered: false,
      images: [imagePaths.bird],
      lead: 'Cedar is a hand-friendly cockatiel with a clear whistle, a calm perch habit, and a very social streak.',
      details: 'He is eating well, used to millet treats, and comfortable with quiet handling once he settles in.',
      fit: 'A practical pick for someone who wants a responsive bird without jumping straight to a larger parrot.',
    },
    {
      title: 'Indigo - Sun Conure',
      petName: 'Indigo',
      species: 'Bird',
      breed: 'Sun Conure',
      age: '15 Months',
      gender: 'Female',
      size: 'Small',
      price: 890,
      location: 'Orlando, FL',
      category: 'pets',
      listingType: 'fixed',
      images: [imagePaths.bird],
      lead: 'Indigo is a bright Sun Conure with bold color, high energy, and an eager bond to the people she trusts.',
      details: 'She is healthy, well socialized, and already comfortable with toys, short training sessions, and a regular light cycle.',
      fit: 'A strong fit for an experienced bird home that can offer time, noise tolerance, and daily interaction.',
    },
  ];

  const sarahLivestockItems = [
    {
      title: 'Ember - Rhode Island Red Trio',
      petName: 'Ember',
      species: 'Poultry',
      breed: 'Rhode Island Red',
      age: '6 Months',
      gender: 'Female',
      size: 'Small',
      price: 145,
      location: 'Austin, TX',
      category: 'livestock',
      listingType: 'auction',
      lotSize: 3,
      images: [imagePaths.bird],
      lead: 'Ember is a tidy trio of Rhode Island Reds that are already producing steady, reliable barnyard energy.',
      details: 'They are healthy, coop trained, and comfortable with feeders, roosts, and calm daily handling.',
      fit: 'A smart starter lot for a backyard flock that wants dependable layers without a lot of fuss.',
    },
    {
      title: 'Hazel - Buff Orpington Quartet',
      petName: 'Hazel',
      species: 'Poultry',
      breed: 'Buff Orpington',
      age: '5 Months',
      gender: 'Female',
      size: 'Small',
      price: 175,
      location: 'Dallas, TX',
      category: 'livestock',
      listingType: 'auction',
      lotSize: 4,
      images: [imagePaths.bird],
      lead: 'Hazel is a calm Buff Orpington quartet with soft feathers, easy handling, and a friendly coop temperament.',
      details: 'They are used to a clean run, daily feed checks, and a quiet rhythm around kids and other barn animals.',
      fit: 'Best for a family flock that wants gentle birds and a practical egg basket.',
    },
    {
      title: 'Penny - Barred Rock Six-Pack',
      petName: 'Penny',
      species: 'Poultry',
      breed: 'Barred Plymouth Rock',
      age: '7 Months',
      gender: 'Female',
      size: 'Small',
      price: 210,
      location: 'San Antonio, TX',
      category: 'livestock',
      listingType: 'auction',
      lotSize: 6,
      images: [imagePaths.bird],
      lead: 'Penny is a strong six-pack of Barred Rocks with good color, consistent laying potential, and a sturdy build.',
      details: 'They are healthy, weather hardy, and already familiar with roosts, scratch feed, and outdoor space.',
      fit: 'A practical choice for someone who wants a larger backyard flock that can handle regular use.',
    },
    {
      title: 'Marigold - Ameraucana Pair',
      petName: 'Marigold',
      species: 'Poultry',
      breed: 'Ameraucana',
      age: '8 Months',
      gender: 'Female',
      size: 'Small',
      price: 160,
      location: 'Boise, ID',
      category: 'livestock',
      listingType: 'auction',
      lotSize: 2,
      images: [imagePaths.bird],
      lead: 'Marigold is a colorful Ameraucana pair with steady personalities and a nice egg-laying profile.',
      details: 'They are healthy, handled daily, and already used to a simple coop, waterer, and feed routine.',
      fit: 'A clean fit for someone who wants a small but distinctive pair of hens.',
    },
    {
      title: 'Scout - Pekin Duck Pair',
      petName: 'Scout',
      species: 'Poultry',
      breed: 'Pekin Duck',
      age: '4 Months',
      gender: 'Pair',
      size: 'Small',
      price: 120,
      location: 'Baton Rouge, LA',
      category: 'livestock',
      listingType: 'auction',
      lotSize: 2,
      images: [imagePaths.bird],
      lead: 'Scout is a friendly Pekin duck pair with a clean bill, soft plumage, and a fast-growing frame.',
      details: 'They are healthy, used to water dishes and feed trays, and comfortable with a backyard pond or trough.',
      fit: 'Best for someone who wants ducks that are easy to keep and quick to settle in.',
    },
  ];

  const jamesItems = [
    {
      title: 'Nina - Bengal',
      petName: 'Nina',
      species: 'Cat',
      breed: 'Bengal',
      age: '8 Months',
      gender: 'Female',
      size: 'Medium',
      price: 1450,
      location: 'Seattle, WA',
      category: 'pets',
      listingType: 'fixed',
      vaccinated: true,
      neutered: false,
      images: [imagePaths.cat],
      lead: 'Nina is an energetic Bengal kitten with a striking coat and a love for climbing, chasing, and exploring.',
      details: 'She is litter trained, vaccinated, and used to active play with wand toys and sturdy cat trees.',
      fit: 'Best for a home that wants a high-engagement cat with a lot of personality and room to move.',
    },
    {
      title: 'Marlow - Scottish Fold',
      petName: 'Marlow',
      species: 'Cat',
      breed: 'Scottish Fold',
      age: '2 Years',
      gender: 'Male',
      size: 'Medium',
      price: 1180,
      location: 'Portland, OR',
      category: 'pets',
      listingType: 'fixed',
      vaccinated: true,
      neutered: true,
      images: [imagePaths.cat],
      lead: 'Marlow is a soft-spoken Scottish Fold with a round face, a calm routine, and a loyal people-first nature.',
      details: 'He is vaccinated, neutered, and happy with a predictable home that keeps his space tidy and low stress.',
      fit: 'A dependable option for someone who wants a quiet cat that settles in quickly.',
    },
    {
      title: 'Violet - Tuxedo Cat',
      petName: 'Violet',
      species: 'Cat',
      breed: 'Tuxedo',
      age: '5 Years',
      gender: 'Female',
      size: 'Medium',
      price: 290,
      location: 'Milwaukee, WI',
      category: 'pets',
      listingType: 'fixed',
      vaccinated: true,
      neutered: true,
      images: [imagePaths.cat],
      lead: 'Violet is a confident tuxedo cat with a polished look and a steady, affectionate home-cat rhythm.',
      details: 'She is fixed, vaccinated, litter trained, and relaxed around normal household noise and visitors.',
      fit: 'A nice fit for an adopter who wants a mature companion instead of a kitten project.',
    },
    {
      title: 'Otis - Maine Coon',
      petName: 'Otis',
      species: 'Cat',
      breed: 'Maine Coon',
      age: '9 Months',
      gender: 'Male',
      size: 'Large',
      price: 1325,
      location: 'Boise, ID',
      category: 'pets',
      listingType: 'fixed',
      vaccinated: true,
      neutered: false,
      images: [imagePaths.cat],
      lead: 'Otis is a big Maine Coon kitten with a fluffy tail, a playful streak, and a surprisingly calm nap schedule.',
      details: 'He is healthy, socialized, and already comfortable with brushing, stairs, and a busy family room.',
      fit: 'Great for a home that wants a handsome cat who will grow into a gentle, oversized companion.',
    },
    {
      title: 'Hazel - Rescue Tabby',
      petName: 'Hazel',
      species: 'Cat',
      breed: 'Tabby Mix',
      age: '3 Years',
      gender: 'Female',
      size: 'Medium',
      price: 240,
      location: 'Kansas City, MO',
      category: 'pets',
      listingType: 'fixed',
      vaccinated: true,
      neutered: true,
      images: [imagePaths.cat],
      lead: 'Hazel is a warm, steady tabby with an easy lap-cat habit and a friendly greeting for new people.',
      details: 'She is spayed, vaccinated, litter trained, and happiest with a soft bed and a routine feeding window.',
      fit: 'A practical rescue companion for a home that values calm energy and low maintenance.',
    },
    {
      title: 'Tobias - American Shorthair',
      petName: 'Tobias',
      species: 'Cat',
      breed: 'American Shorthair',
      age: '4 Months',
      gender: 'Male',
      size: 'Small',
      price: 420,
      location: 'Des Moines, IA',
      category: 'pets',
      listingType: 'fixed',
      vaccinated: true,
      neutered: false,
      images: [imagePaths.cat],
      lead: 'Tobias is a bright-eyed kitten with a quick pounce, a friendly curiosity, and a very easy purr.',
      details: 'He is vaccinated, healthy, and already learning crate-free home manners, litter box habits, and gentle handling.',
      fit: 'Best for someone who wants a lively kitten and is ready for the usual early training.',
    },
    {
      title: 'Ellis - Russian Blue',
      petName: 'Ellis',
      species: 'Cat',
      breed: 'Russian Blue',
      age: '18 Months',
      gender: 'Male',
      size: 'Medium',
      price: 1040,
      location: 'Salt Lake City, UT',
      category: 'pets',
      listingType: 'fixed',
      vaccinated: true,
      neutered: true,
      images: [imagePaths.cat],
      lead: 'Ellis is a cool-toned Russian Blue with a quiet presence, a neat coat, and a strong bond to one or two people.',
      details: 'He is neutered, vaccinated, and used to a calm home with routine meals and a clean litter area.',
      fit: 'A good fit for an apartment or a quieter household that wants a thoughtful, low-drama cat.',
    },
    {
      title: 'Cora - Lop Rabbit',
      petName: 'Cora',
      species: 'Rabbit',
      breed: 'Mini Lop',
      age: '7 Months',
      gender: 'Female',
      size: 'Small',
      price: 165,
      location: 'Madison, WI',
      category: 'pets',
      listingType: 'fixed',
      vaccinated: false,
      neutered: false,
      images: [imagePaths.rabbit],
      lead: 'Cora is a tiny Mini Lop with velvety ears, a quiet hop, and a relaxed way of settling once she is comfortable.',
      details: 'She is litter box trained, healthy, and already used to hay, pellets, and daily gentle handling.',
      fit: 'A strong match for someone who wants a rabbit that can live comfortably indoors with the right setup.',
    },
    {
      title: 'Benny - Rex Rabbit',
      petName: 'Benny',
      species: 'Rabbit',
      breed: 'Mini Rex',
      age: '1 Year',
      gender: 'Male',
      size: 'Small',
      price: 150,
      location: 'Reno, NV',
      category: 'pets',
      listingType: 'fixed',
      vaccinated: false,
      neutered: true,
      images: [imagePaths.rabbit],
      lead: 'Benny is a velvety Mini Rex with a clean coat, a curious nose, and a calm attitude around handling.',
      details: 'He is used to a structured feeding routine, a tidy enclosure, and short daily floor time for exercise.',
      fit: 'Best for a home that wants a low-noise companion and can keep up with proper rabbit care.',
    },
    {
      title: 'Opal - Flemish Giant',
      petName: 'Opal',
      species: 'Rabbit',
      breed: 'Flemish Giant',
      age: '10 Months',
      gender: 'Female',
      size: 'Large',
      price: 360,
      location: 'Eugene, OR',
      category: 'pets',
      listingType: 'fixed',
      status: 'pending',
      vaccinated: false,
      neutered: false,
      images: [imagePaths.rabbit],
      lead: 'Opal is a gentle Flemish Giant with a relaxed hop, a big frame, and a very soft temperament.',
      details: 'She is healthy, hay-focused, and already accustomed to calm handling and a roomy exercise area.',
      fit: 'A good fit for an experienced rabbit home that can support a larger enclosure and regular grooming.',
    },
    {
      title: 'Coco - Cochin Bantam Pair',
      petName: 'Coco',
      species: 'Bird',
      breed: 'Cochin Bantam Pair',
      age: '5 Months',
      gender: 'Pair',
      size: 'Small',
      price: 120,
      location: 'Tallahassee, FL',
      category: 'pets',
      listingType: 'fixed',
      images: [imagePaths.bird],
      lead: 'Coco is a bonded pair of small bantams with a soft, easygoing routine and a charming backyard presence.',
      details: 'They are healthy, used to coop time, and comfortable with daily checks, feed trays, and gentle pickup.',
      fit: 'Best for a hobby keeper who wants a decorative pair that still behaves like a practical backyard bird.',
    },
    {
      title: 'Willow - Finch Trio',
      petName: 'Willow',
      species: 'Bird',
      breed: 'Zebra Finch Trio',
      age: '8 Months',
      gender: 'Trio',
      size: 'Small',
      price: 140,
      location: 'Tucson, AZ',
      category: 'pets',
      listingType: 'fixed',
      images: [imagePaths.bird],
      lead: 'Willow is a lively trio of zebra finches with steady song, quick movement, and low-maintenance care.',
      details: 'They are healthy, used to a clean aviary, and comfortable around a consistent feeding and watering routine.',
      fit: 'A nice fit for someone who wants active small birds without a large cage or complex diet.',
    },
    {
      title: 'Jasper - Quaker Pair',
      petName: 'Jasper',
      species: 'Bird',
      breed: 'Quaker Parakeet Pair',
      age: '2 Years',
      gender: 'Pair',
      size: 'Small',
      price: 620,
      location: 'Charlotte, NC',
      category: 'pets',
      listingType: 'fixed',
      images: [imagePaths.bird],
      lead: 'Jasper is a bonded pair of Quaker parrots with a lot of personality and a steady daily rhythm.',
      details: 'They are healthy, hand-friendly, and already used to a clean cage setup with toys and short training sessions.',
      fit: 'Best for an attentive bird home that wants a chatty, interactive pair.',
    },
  ];

  const jamesLivestockItems = [
    {
      title: 'Mabel - Mini Nubian Doe Kid',
      petName: 'Mabel',
      species: 'Goat',
      breed: 'Mini Nubian',
      age: '4 Months',
      gender: 'Female',
      size: 'Small',
      price: 220,
      location: 'Des Moines, IA',
      category: 'livestock',
      listingType: 'auction',
      lotSize: 1,
      images: [imagePaths.livestock],
      lead: 'Mabel is a bright Mini Nubian kid with a friendly bounce and a very manageable size for a small farm.',
      details: 'She is healthy, bottle trained, and already comfortable around leads, gates, and daily handling.',
      fit: 'A great starter goat for a homestead that wants an easygoing doe to raise and train.',
    },
    {
      title: 'Gus - Katahdin Lamb Pair',
      petName: 'Gus',
      species: 'Sheep',
      breed: 'Katahdin',
      age: '5 Months',
      gender: 'Pair',
      size: 'Medium',
      price: 260,
      location: 'Lincoln, NE',
      category: 'livestock',
      listingType: 'auction',
      lotSize: 2,
      images: [imagePaths.livestock],
      lead: 'Gus is a calm pair of Katahdin lambs with a sturdy build and a simple, low-maintenance pasture style.',
      details: 'They are used to hay, mineral blocks, and light handling without getting stressed or pushy.',
      fit: 'Best for a small acreage buyer who wants practical sheep without a complicated wool routine.',
    },
    {
      title: 'Tansy - Heritage Piglet Pair',
      petName: 'Tansy',
      species: 'Swine',
      breed: 'Heritage Piglet Pair',
      age: '3 Months',
      gender: 'Pair',
      size: 'Small',
      price: 190,
      location: 'Springfield, MO',
      category: 'livestock',
      listingType: 'auction',
      lotSize: 2,
      images: [imagePaths.livestock],
      lead: 'Tansy is a sturdy pair of heritage piglets with a good appetite and a very steady feed response.',
      details: 'They are healthy, used to a clean pen, and already comfortable around routine barn work and water buckets.',
      fit: 'A practical buy for a family finishing pigs or building out a small farm hog project.',
    },
    {
      title: 'Rowan - Dairy Goat Doe',
      petName: 'Rowan',
      species: 'Goat',
      breed: 'Nigerian Dwarf',
      age: '2 Years',
      gender: 'Female',
      size: 'Small',
      price: 335,
      location: 'Bozeman, MT',
      category: 'livestock',
      listingType: 'auction',
      lotSize: 1,
      images: [imagePaths.livestock],
      lead: 'Rowan is a compact dairy doe with a calm personality, good body condition, and easy milking potential.',
      details: 'She is vaccinated, healthy, and used to stanchions, grain bowls, and steady farm routines.',
      fit: 'A strong match for a homestead that wants a smaller dairy goat with practical daily use.',
    },
    {
      title: 'Fern - Bottle Calf Pair',
      petName: 'Fern',
      species: 'Cattle',
      breed: 'Bottle Calf Pair',
      age: '6 Weeks',
      gender: 'Pair',
      size: 'Medium',
      price: 340,
      location: 'Salina, KS',
      category: 'livestock',
      listingType: 'auction',
      lotSize: 2,
      images: [imagePaths.livestock],
      lead: 'Fern is a pair of bottle calves that are healthy, alert, and ready for a buyer who wants to raise them right.',
      details: 'They are fed on schedule, easy to handle, and already accustomed to halters, buckets, and daily checks.',
      fit: 'Best for a small farm looking for a simple, hands-on calf project.',
    },
  ];

  const mariaItems = [
    {
      title: 'Maribel - Jersey Milk Cow',
      petName: 'Maribel',
      species: 'Cattle',
      breed: 'Jersey',
      age: '3 Years',
      gender: 'Female',
      size: 'Large',
      price: 6850,
      location: 'Fresno, CA',
      category: 'livestock',
      listingType: 'auction',
      vaccinated: true,
      neutered: false,
      images: [imagePaths.livestock],
      lead: 'Maribel is a docile Jersey milk cow with a strong udder, a clean frame, and an easy lead on the halter.',
      details: 'She is vet-checked, pasture raised, and used to a regular milking schedule, feed buckets, and trailer loading.',
      fit: 'A practical fit for a family dairy setup or a small farm that wants steady milk production.',
    },
    {
      title: 'Buck - Black Angus Heifer',
      petName: 'Buck',
      species: 'Cattle',
      breed: 'Black Angus',
      age: '16 Months',
      gender: 'Female',
      size: 'Large',
      price: 5200,
      location: 'Omaha, NE',
      category: 'livestock',
      listingType: 'auction',
      vaccinated: true,
      neutered: false,
      images: [imagePaths.livestock],
      lead: 'Buck is a sturdy Black Angus heifer with a balanced frame and a calm way of moving through the lot.',
      details: 'She is clean, parasite-managed, and familiar with fence lines, grain bins, and routine handling.',
      fit: 'A strong choice for a rancher looking to grow out a dependable beef animal.',
    },
    {
      title: 'Nora - Highland Heifer',
      petName: 'Nora',
      species: 'Cattle',
      breed: 'Highland',
      age: '2 Years',
      gender: 'Female',
      size: 'Large',
      price: 9100,
      location: 'Asheville, NC',
      category: 'livestock',
      listingType: 'auction',
      vaccinated: true,
      neutered: false,
      images: [imagePaths.livestock],
      lead: 'Nora is a shaggy Highland heifer with a gentle eye, thick coat, and a very steady pasture temperament.',
      details: 'She is halter-broke, vaccinated, and used to wet weather, brush, and regular herd movement.',
      fit: 'Best for a farm that wants a hardy, showy cow with strong pasture presence.',
    },
    {
      title: 'Briar - Hereford Pair',
      petName: 'Briar',
      species: 'Cattle',
      breed: 'Hereford',
      age: '4 Years',
      gender: 'Female',
      size: 'Large',
      price: 12400,
      location: 'Cheyenne, WY',
      category: 'livestock',
      listingType: 'auction',
      images: [imagePaths.livestock],
      lead: 'Briar is a bred Hereford cow with a strong frame, a patient nature, and a very clean udder line.',
      details: 'She is herd-raised, trailer friendly, and comfortable around routine veterinary checks and feed changes.',
      fit: 'A practical buy for a ranch that wants a calm cow with solid maternal potential.',
    },
    {
      title: 'Canyon - Dexter Cow',
      petName: 'Canyon',
      species: 'Cattle',
      breed: 'Dexter',
      age: '5 Years',
      gender: 'Female',
      size: 'Medium',
      price: 7600,
      location: 'Boise, ID',
      category: 'livestock',
      listingType: 'auction',
      images: [imagePaths.livestock],
      lead: 'Canyon is a smaller Dexter cow with easy handling, a compact body, and strong efficiency for a homestead.',
      details: 'She is vaccinated, settled on grass and hay, and used to regular human contact without being pushy.',
      fit: 'A good fit for a small farm that wants a manageable cow without the size of a full commercial animal.',
    },
    {
      title: 'Pine - Nubian Goat Doe',
      petName: 'Pine',
      species: 'Goat',
      breed: 'Nubian',
      age: '2 Years',
      gender: 'Female',
      size: 'Medium',
      price: 430,
      location: 'Raleigh, NC',
      category: 'livestock',
      listingType: 'auction',
      vaccinated: true,
      neutered: false,
      images: [imagePaths.livestock],
      lead: 'Pine is a vocal Nubian doe with long ears, a friendly approach, and strong milk-line genetics.',
      details: 'She is herd-socialized, vaccinated, and used to browse, grain, and daily pen checks.',
      fit: 'Best for a small dairy setup or a farm that wants a personable goat with good presence.',
    },
    {
      title: 'Sage - Boer Wether',
      petName: 'Sage',
      species: 'Goat',
      breed: 'Boer',
      age: '10 Months',
      gender: 'Male',
      size: 'Medium',
      price: 280,
      location: 'Tulsa, OK',
      category: 'livestock',
      listingType: 'auction',
      images: [imagePaths.livestock],
      lead: 'Sage is a solid Boer wether with a sturdy build, good feed conversion, and a friendly barnyard attitude.',
      details: 'He is vaccinated, easy to lead, and used to brush, gates, and a simple daily feed routine.',
      fit: 'A practical fit for brush control, 4-H practice, or a companion goat project.',
    },
    {
      title: 'Faye - Nigerian Dwarf Doe',
      petName: 'Faye',
      species: 'Goat',
      breed: 'Nigerian Dwarf',
      age: '18 Months',
      gender: 'Female',
      size: 'Small',
      price: 315,
      location: 'Santa Fe, NM',
      category: 'livestock',
      listingType: 'auction',
      images: [imagePaths.livestock],
      lead: 'Faye is a compact Nigerian Dwarf doe with a bright eye, an easy milking frame, and quick feet.',
      details: 'She is healthy, vaccinated, and already used to stanchions, grain buckets, and close handling.',
      fit: 'A good choice for a backyard milker or a homestead that prefers a smaller goat.',
    },
    {
      title: 'Murphy - Pasture Piglet Pair',
      petName: 'Murphy',
      species: 'Swine',
      breed: 'Pasture Piglet Pair',
      age: '3 Months',
      gender: 'Pair',
      size: 'Small',
      price: 220,
      location: 'Fayetteville, AR',
      category: 'livestock',
      listingType: 'auction',
      images: [imagePaths.livestock],
      lead: 'Murphy is a calm pair of pasture piglets with a sturdy appetite and easy handling around feed tubs.',
      details: 'They are healthy, used to fence lines, and already comfortable with routine checks and simple barn noise.',
      fit: 'Best for a small producer or a family finishing pigs for the freezer.',
    },
    {
      title: 'Lark - Nubian Doe Kid',
      petName: 'Lark',
      species: 'Goat',
      breed: 'Nubian',
      age: '5 Months',
      gender: 'Female',
      size: 'Small',
      price: 190,
      location: 'Bend, OR',
      category: 'livestock',
      listingType: 'auction',
      images: [imagePaths.livestock],
      status: 'pending',
      lead: 'Lark is a young Nubian doe kid with a bright gait, a friendly face, and a very manageable size.',
      details: 'She is bottle trained, healthy, and already used to a clean pen, hay feeder, and regular handling.',
      fit: 'A nice fit for a homestead that wants to raise a friendly doe from the ground up.',
    },
    {
      title: 'Milo - Pygmy Goat Wether',
      petName: 'Milo',
      species: 'Goat',
      breed: 'Pygmy',
      age: '7 Months',
      gender: 'Male',
      size: 'Small',
      price: 165,
      location: 'Mobile, AL',
      category: 'livestock',
      listingType: 'auction',
      images: [imagePaths.livestock],
      lead: 'Milo is a compact Pygmy wether with a playful hop and a very easy backyard temperament.',
      details: 'He is vaccinated, handled daily, and comfortable around kids, halters, and small pasture moves.',
      fit: 'A practical companion animal or light brush-control helper for a small acreage.',
    },
    {
      title: 'Junie - Brown Swiss Heifer',
      petName: 'Junie',
      species: 'Cattle',
      breed: 'Brown Swiss',
      age: '14 Months',
      gender: 'Female',
      size: 'Large',
      price: 5900,
      location: 'Madison, WI',
      category: 'livestock',
      listingType: 'auction',
      images: [imagePaths.livestock],
      lead: 'Junie is a long-bodied Brown Swiss heifer with a calm step and a solid frame for dairy or breeding.',
      details: 'She is clean, vaccinated, and used to barn routines, lead ropes, and regular feed changes.',
      fit: 'A strong fit for a farm wanting a steady heifer with room to grow.',
    },
    {
      title: 'Harbor - Mini Jersey Cow',
      petName: 'Harbor',
      species: 'Cattle',
      breed: 'Mini Jersey',
      age: '2 Years',
      gender: 'Female',
      size: 'Medium',
      price: 8400,
      location: 'Lexington, KY',
      category: 'livestock',
      listingType: 'auction',
      images: [imagePaths.livestock],
      lead: 'Harbor is a compact Mini Jersey with a friendly face, easy handling, and strong homestead milk potential.',
      details: 'She is vaccinated, halter broke, and already used to hand feeding, barn runs, and trailer space.',
      fit: 'Best for a family farm that wants small-scale dairy without a full-size cow footprint.',
    },
  ];

  const jamesSupplyItems = [
    {
      title: 'CoopGuard - Disinfectant 6-Pack',
      petName: 'CoopGuard',
      species: 'Hygiene',
      breed: 'Commercial Sanitizer',
      age: 'New',
      gender: 'Case',
      size: 'Large',
      price: 84,
      location: 'Seattle, WA',
      category: 'supplies',
      listingType: 'fixed',
      lotSize: 6,
      allowPartialSale: true,
      images: [imagePaths.supplies],
      lead: 'CoopGuard is a clean, barn-safe disinfectant pack for runs, crates, and routine deep-clean days.',
      details: 'It is easy to spray, quick to wipe, and built for sellers who want a no-fuss sanitation routine.',
      fit: 'A practical purchase for any breeder or backyard keeper that needs reliable cleanup between animals.',
    },
    {
      title: 'NestSafe - Bedding Bale',
      petName: 'NestSafe',
      species: 'Bedding',
      breed: 'Compressed Straw Bale',
      age: 'New',
      gender: 'Bale',
      size: 'Bulk',
      price: 52,
      location: 'Tacoma, WA',
      category: 'supplies',
      listingType: 'fixed',
      lotSize: 1,
      images: [imagePaths.supplies],
      lead: 'NestSafe is a dry, compressed straw bale that keeps stalls, hutches, and brooder areas tidy.',
      details: 'It breaks apart cleanly, stores well, and gives you a simple bedding option with low waste.',
      fit: 'Best for anyone who wants an affordable bedding base for small animals and poultry.',
    },
    {
      title: 'PawPort - Folding Carrier',
      petName: 'PawPort',
      species: 'Transport',
      breed: 'Soft-Side Carrier',
      age: 'New',
      gender: 'Unit',
      size: 'Medium',
      price: 68,
      location: 'Bellevue, WA',
      category: 'supplies',
      listingType: 'fixed',
      images: [imagePaths.supplies, imagePaths.cat],
      lead: 'PawPort is a compact folding carrier for cats, small rabbits, and quick vet trips.',
      details: 'It has a rigid base, breathable panels, and a shape that stores flat when you are not using it.',
      fit: 'A good buy for adopters who need a safe, tidy way to move a smaller companion.',
    },
    {
      title: 'AquaFlow - 5 Gallon Waterer',
      petName: 'AquaFlow',
      species: 'Feeding',
      breed: 'Automatic Waterer',
      age: 'New',
      gender: 'Unit',
      size: 'Large',
      price: 92,
      location: 'Madison, WI',
      category: 'supplies',
      listingType: 'fixed',
      images: [imagePaths.supplies],
      lead: 'AquaFlow is a sturdy five-gallon waterer that keeps small-farm animals supplied without constant refilling.',
      details: 'It is simple to clean, weather resistant, and sized for coops, hutches, and small pens.',
      fit: 'Best for keepers who want to reduce daily chores and keep water available through busy days.',
    },
    {
      title: 'LayerBoost - 40 lb Feed Sack',
      petName: 'LayerBoost',
      species: 'Nutrition',
      breed: 'Layer Pellet',
      age: 'New',
      gender: 'Bag',
      size: 'Bulk',
      price: 38,
      location: 'Des Moines, IA',
      category: 'supplies',
      listingType: 'fixed',
      lotSize: 40,
      images: [imagePaths.supplies],
      lead: 'LayerBoost is a dependable layer pellet for hens that need steady nutrition and consistent egg output.',
      details: 'The bag seals well, stores cleanly, and works for backyard flocks that want a practical feed staple.',
      fit: 'A good everyday purchase for poultry keepers who prefer simple, balanced rations.',
    },
    {
      title: 'CalfStart - Milk Replacer',
      petName: 'CalfStart',
      species: 'Nutrition',
      breed: 'Milk Replacer',
      age: 'New',
      gender: 'Bag',
      size: 'Bulk',
      price: 74,
      location: 'Fresno, CA',
      category: 'supplies',
      listingType: 'fixed',
      lotSize: 25,
      images: [imagePaths.supplies],
      lead: 'CalfStart is a dependable milk replacer for bottle calves, early weaning, or backup feeding plans.',
      details: 'It mixes smoothly, stores well, and gives young stock a predictable formula when real milk is not practical.',
      fit: 'Best for cattle owners who want a shelf-stable option for young animals.',
    },
    {
      title: 'ShedShield - Fly Spray Case',
      petName: 'ShedShield',
      species: 'Healthcare',
      breed: 'Fly Control',
      age: 'New',
      gender: 'Case',
      size: 'Large',
      price: 110,
      location: 'Oklahoma City, OK',
      category: 'supplies',
      listingType: 'fixed',
      lotSize: 12,
      images: [imagePaths.supplies],
      lead: 'ShedShield is a case of fly spray meant for barns, trailers, and warm-weather pens.',
      details: 'It is easy to apply, long-lasting, and a practical part of keeping animals calmer in the summer.',
      fit: 'A useful pick for anyone running livestock or poultry through humid months.',
    },
    {
      title: 'HaloClip - ID Collar Set',
      petName: 'HaloClip',
      species: 'Accessories',
      breed: 'Nylon Collar Set',
      age: 'New',
      gender: 'Pack',
      size: 'Small',
      price: 46,
      location: 'Nashville, TN',
      category: 'supplies',
      listingType: 'fixed',
      lotSize: 10,
      images: [imagePaths.supplies],
      lead: 'HaloClip is a set of nylon ID collars for puppies, cats in transit, and small-farm handling.',
      details: 'The clips are simple, color-coded, and easy to swap when you are sorting multiple animals at once.',
      fit: 'Best for a seller who likes to keep a clean, organized kennel or barn setup.',
    },
    {
      title: 'BarnBright - LED Work Light',
      petName: 'BarnBright',
      species: 'Hardware',
      breed: 'LED Work Light',
      age: 'New',
      gender: 'Unit',
      size: 'Large',
      price: 120,
      location: 'Boise, ID',
      category: 'supplies',
      listingType: 'fixed',
      images: [imagePaths.supplies],
      lead: 'BarnBright is a bright LED work light for early chores, evening checks, and tack-room repairs.',
      details: 'It is tough, weather aware, and made for sellers who need clear light in less-than-perfect conditions.',
      fit: 'A straightforward utility piece for anyone working around animals after dark.',
    },
    {
      title: 'CoopSafe - Predator Netting',
      petName: 'CoopSafe',
      species: 'Housing',
      breed: 'Heavy-Duty Netting',
      age: 'New',
      gender: 'Roll',
      size: 'Large',
      price: 165,
      location: 'Charlotte, NC',
      category: 'supplies',
      listingType: 'fixed',
      lotSize: 1,
      images: [imagePaths.supplies],
      lead: 'CoopSafe is a heavy-duty netting roll for securing poultry runs, rabbit pens, and light pasture edges.',
      details: 'It is built to trim cleanly, hold tension, and make a basic predator barrier without much hassle.',
      fit: 'A solid choice for keepers who want practical protection without overbuilding the fence.',
    },
    {
      title: 'PurrPortion - Auto Feeder',
      petName: 'PurrPortion',
      species: 'Feeding',
      breed: 'Smart Feeder',
      age: 'New',
      gender: 'Unit',
      size: 'Medium',
      price: 98,
      location: 'Kansas City, MO',
      category: 'supplies',
      listingType: 'fixed',
      images: [imagePaths.supplies, imagePaths.cat],
      lead: 'PurrPortion is a tidy automatic feeder for cats, rabbits, or any indoor pet that needs reliable meal timing.',
      details: 'It is simple to program, easy to clean, and helps keep portions consistent when routines get busy.',
      fit: 'Best for owners who want to keep mealtimes steady even when they are away from home.',
    },
    {
      title: 'HoofGuard - Mineral Block 12-Pack',
      petName: 'HoofGuard',
      species: 'Supplements',
      breed: 'Mineral Block',
      age: 'New',
      gender: 'Pack',
      size: 'Bulk',
      price: 72,
      location: 'Lexington, KY',
      category: 'supplies',
      listingType: 'fixed',
      lotSize: 12,
      images: [imagePaths.supplies],
      lead: 'HoofGuard is a 12-pack of mineral blocks for cattle, goats, and other pasture animals.',
      details: 'The blocks are weather resistant, easy to place, and meant to support a simple grazing routine.',
      fit: 'A practical staple for farms that want to keep minerals available without daily measuring.',
    },
    {
      title: 'TrailMate - Livestock Ramp',
      petName: 'TrailMate',
      species: 'Transport',
      breed: 'Aluminum Ramp',
      age: 'New',
      gender: 'Unit',
      size: 'Large',
      price: 210,
      location: 'Tulsa, OK',
      category: 'supplies',
      listingType: 'fixed',
      images: [imagePaths.supplies],
      lead: 'TrailMate is a lightweight aluminum ramp for loading goats, calves, and small farm equipment.',
      details: 'It locks up neatly, handles regular use, and helps keep loading safer when you are short on help.',
      fit: 'A good buy for sellers who move animals between pasture, trailer, and barn on a regular basis.',
    },
    {
      title: 'NestNest - Brooder Heat Lamp',
      petName: 'NestNest',
      species: 'Brooding',
      breed: 'Heat Lamp',
      age: 'New',
      gender: 'Unit',
      size: 'Small',
      price: 58,
      location: 'Fayetteville, AR',
      category: 'supplies',
      listingType: 'fixed',
      images: [imagePaths.supplies],
      lead: 'NestNest is a reliable brooder heat lamp for chicks, ducklings, and any small flock that needs warmth.',
      details: 'It is simple to hang, easy to aim, and built for everyday use in a clean brood area.',
      fit: 'Best for poultry keepers who want a practical starter setup for young birds.',
    },
    {
      title: 'BrushBrite - Grooming Kit',
      petName: 'BrushBrite',
      species: 'Grooming',
      breed: 'Professional Grooming Set',
      age: 'New',
      gender: 'Kit',
      size: 'Medium',
      price: 64,
      location: 'Miami, FL',
      category: 'supplies',
      listingType: 'fixed',
      images: [imagePaths.supplies],
      lead: 'BrushBrite is a simple grooming kit for cats, dogs, and show-ready rabbits that need regular coat care.',
      details: 'The set is compact, easy to store, and designed to keep a daily brush-out from feeling like a chore.',
      fit: 'A useful add-on for any household that wants to keep coats tidy between baths or show days.',
    },
  ];

  const mariaBirdItems = [
    {
      title: 'Azure - Parakeet Pair',
      petName: 'Azure',
      species: 'Bird',
      breed: 'Budgerigar Pair',
      age: '8 Months',
      gender: 'Pair',
      size: 'Small',
      price: 190,
      location: 'Tampa, FL',
      category: 'pets',
      listingType: 'fixed',
      images: [imagePaths.bird],
      lead: 'Bluebell is a bonded pair of bright parakeets with a cheerful chatter and an easy, homey presence.',
      details: 'They are healthy, used to a routine feeding schedule, and accustomed to a covered cage with daily attention.',
      fit: 'Best for a home that wants a small, lively pet bird with a steady soundtrack.',
    },
    {
      title: 'Harbor - Cockatiel',
      petName: 'Harbor',
      species: 'Bird',
      breed: 'Cockatiel',
      age: '2 Years',
      gender: 'Male',
      size: 'Small',
      price: 420,
      location: 'Phoenix, AZ',
      category: 'pets',
      listingType: 'fixed',
      images: [imagePaths.bird],
      lead: 'Cedar is a hand-friendly cockatiel with a clear whistle, a calm perch habit, and a very social streak.',
      details: 'He is eating well, used to millet treats, and comfortable with quiet handling once he settles in.',
      fit: 'A practical pick for someone who wants a responsive bird without jumping straight to a larger parrot.',
    },
    {
      title: 'Solstice - Sun Conure',
      petName: 'Solstice',
      species: 'Bird',
      breed: 'Sun Conure',
      age: '15 Months',
      gender: 'Female',
      size: 'Small',
      price: 890,
      location: 'Orlando, FL',
      category: 'pets',
      listingType: 'fixed',
      images: [imagePaths.bird],
      lead: 'Indigo is a bright Sun Conure with bold color, high energy, and an eager bond to the people she trusts.',
      details: 'She is healthy, well socialized, and already comfortable with toys, short training sessions, and a regular light cycle.',
      fit: 'A strong fit for an experienced bird home that can offer time, noise tolerance, and daily interaction.',
    },
  ];

  const extraLivestockItems = [
    {
      title: 'Juniper - Alpaca Pair',
      petName: 'Juniper',
      species: 'Alpaca',
      breed: 'Huacaya Pair',
      age: '2 Years',
      gender: 'Pair',
      size: 'Large',
      price: 2400,
      location: 'Durango, CO',
      category: 'livestock',
      listingType: 'auction',
      lotSize: 2,
      images: [imagePaths.livestock],
      lead: 'Juniper is a bonded alpaca pair with clean fleece, quiet manners, and an easy walk on lead.',
      details: 'They are halter trained, used to pasture rotation, and comfortable with routine shearing and handling.',
      fit: 'A good fit for a fiber farm or a homestead that wants a calm, watchful herd animal.',
    },
    {
      title: 'Wren - Royal Palm Turkey Trio',
      petName: 'Wren',
      species: 'Turkey',
      breed: 'Royal Palm',
      age: '7 Months',
      gender: 'Trio',
      size: 'Large',
      price: 225,
      location: 'Athens, GA',
      category: 'livestock',
      listingType: 'auction',
      lotSize: 3,
      images: [imagePaths.bird],
      lead: 'Wren is a lively turkey trio with strong feather patterning, curious energy, and a farmyard presence.',
      details: 'They are coop trained, used to a routine feed bowl, and steady around other birds and small stock.',
      fit: 'Best for a buyer who wants attractive birds that still behave like practical barnyard livestock.',
    },
    {
      title: 'Cedar - Dorper Ewe',
      petName: 'Cedar',
      species: 'Sheep',
      breed: 'Dorper',
      age: '3 Years',
      gender: 'Female',
      size: 'Medium',
      price: 420,
      location: 'Billings, MT',
      category: 'livestock',
      listingType: 'auction',
      lotSize: 1,
      images: [imagePaths.livestock],
      lead: 'Cedar is a solid Dorper ewe with a smooth coat, good body condition, and easy pasture movement.',
      details: 'She is vaccinated, accustomed to mineral tubs, and relaxed around gate work and trailer loading.',
      fit: 'A practical choice for a small flock that wants low-maintenance meat sheep with good structure.',
    },
    {
      title: 'Bramble - Dexter Cow',
      petName: 'Bramble',
      species: 'Cattle',
      breed: 'Dexter',
      age: '4 Years',
      gender: 'Female',
      size: 'Medium',
      price: 7800,
      location: 'Boise, ID',
      category: 'livestock',
      listingType: 'auction',
      images: [imagePaths.livestock],
      lead: 'Bramble is a compact Dexter cow with a calm eye, good grazing efficiency, and a tidy frame for homestead use.',
      details: 'She is halter broke, pasture raised, and used to routine milking checks, barn gates, and simple handling.',
      fit: 'A strong fit for a small dairy or a family wanting a manageable, smaller cow.',
    },
    {
      title: 'Nell - Boer Buckling',
      petName: 'Nell',
      species: 'Goat',
      breed: 'Boer',
      age: '8 Months',
      gender: 'Male',
      size: 'Medium',
      price: 265,
      location: 'Stillwater, OK',
      category: 'livestock',
      listingType: 'auction',
      lotSize: 1,
      images: [imagePaths.livestock],
      lead: 'Nell is a strong Boer buckling with wide shoulders, good weight, and a friendly feed-bucket habit.',
      details: 'He is vaccinated, handled daily, and comfortable with hoof work, leads, and barnyard traffic.',
      fit: 'Useful for brush control, breeding plans, or a 4-H project that needs a solid start.',
    },
    {
      title: 'Mocha - Kunekune Piglet Pair',
      petName: 'Mocha',
      species: 'Swine',
      breed: 'Kunekune',
      age: '10 Weeks',
      gender: 'Pair',
      size: 'Small',
      price: 310,
      location: 'Fayetteville, AR',
      category: 'livestock',
      listingType: 'auction',
      lotSize: 2,
      images: [imagePaths.livestock],
      lead: 'Mocha is a gentle pair of Kunekune piglets with short snouts, round bellies, and easygoing farm manners.',
      details: 'They are used to a clean pen, daily feed buckets, and calm handling around children and other stock.',
      fit: 'A good match for a small homestead wanting pasture-friendly pigs with a sweet temperament.',
    },
    {
      title: 'Pearl - Goose Trio',
      petName: 'Pearl',
      species: 'Goose',
      breed: 'Toulouse',
      age: '5 Months',
      gender: 'Trio',
      size: 'Large',
      price: 195,
      location: 'Lafayette, LA',
      category: 'livestock',
      listingType: 'auction',
      lotSize: 3,
      images: [imagePaths.bird],
      lead: 'Pearl is a watchful goose trio with a strong honk, steady grazing, and excellent yard presence.',
      details: 'They are healthy, accustomed to pond time, and used to moving with a flock through open pasture.',
      fit: 'Best for a buyer who wants natural alarm birds and a practical grazer for the property.',
    },
    {
      title: 'Ash - Miniature Donkey Jenny',
      petName: 'Ash',
      species: 'Donkey',
      breed: 'Miniature Donkey',
      age: '4 Years',
      gender: 'Female',
      size: 'Small',
      price: 1350,
      location: 'Murray, KY',
      category: 'livestock',
      listingType: 'auction',
      lotSize: 1,
      images: [imagePaths.livestock],
      lead: 'Ash is a miniature donkey jenny with a calm step, a soft bray, and a very alert pasture presence.',
      details: 'She is halter trained, vaccinated, and used to being around goats, chickens, and the daily farm routine.',
      fit: 'A useful companion and guardian-style animal for a small farm that wants something personable and practical.',
    },
  ];

  const extraSupplyItems = [
    {
      title: 'FeatherFlow - Automatic Coop Door',
      petName: 'FeatherFlow',
      species: 'Housing',
      breed: 'Auto Door',
      age: 'New',
      gender: 'Unit',
      size: 'Medium',
      price: 189,
      location: 'Athens, GA',
      category: 'supplies',
      listingType: 'fixed',
      images: [imagePaths.supplies],
      lead: 'FeatherFlow is an automatic coop door that opens on schedule and closes when the light drops.',
      details: 'It is weather aware, easy to mount, and a major time-saver for anyone checking hens before work.',
      fit: 'A smart upgrade for poultry keepers who want safer evenings and fewer early wakeups.',
    },
    {
      title: 'HalterHouse - Calf Bottle Rack',
      petName: 'HalterHouse',
      species: 'Feeding',
      breed: 'Bottle Rack',
      age: 'New',
      gender: 'Rack',
      size: 'Large',
      price: 74,
      location: 'Salina, KS',
      category: 'supplies',
      listingType: 'fixed',
      images: [imagePaths.supplies, imagePaths.livestockAlt],
      lead: 'HalterHouse is a sturdy bottle rack that keeps calf feeding organized and a lot less messy.',
      details: 'The rack holds multiple bottles upright, is easy to rinse, and saves a lot of awkward bending during feeding time.',
      fit: 'A practical tool for bottle calf buyers or small farms raising several young animals at once.',
    },
    {
      title: 'RidgeCut - Hoof Trimmer Kit',
      petName: 'RidgeCut',
      species: 'Grooming',
      breed: 'Hoof Care Kit',
      age: 'New',
      gender: 'Kit',
      size: 'Medium',
      price: 96,
      location: 'Bozeman, MT',
      category: 'supplies',
      listingType: 'fixed',
      images: [imagePaths.supplies],
      lead: 'RidgeCut is a practical hoof trimming kit for goats, sheep, and smaller cattle maintenance work.',
      details: 'It includes the basics for routine trims and keeps tools in one place between barn sessions.',
      fit: 'Best for keepers who want to stay ahead of hoof care instead of scrambling when it is overdue.',
    },
    {
      title: 'MossLine - Electric Fence Energizer',
      petName: 'MossLine',
      species: 'Hardware',
      breed: 'Fence Energizer',
      age: 'New',
      gender: 'Unit',
      size: 'Large',
      price: 240,
      location: 'Billings, MT',
      category: 'supplies',
      listingType: 'fixed',
      images: [imagePaths.supplies, imagePaths.livestock],
      lead: 'MossLine is a reliable fence energizer for rotating pastures and keeping curious animals where they belong.',
      details: 'It is built for steady output, simple wiring, and a clean install on a working fence line.',
      fit: 'A useful core tool for anyone managing goats, cattle, or mixed livestock pasture.',
    },
    {
      title: 'NestWorx - Nesting Box Four-Pack',
      petName: 'NestWorx',
      species: 'Housing',
      breed: 'Nested Box Set',
      age: 'New',
      gender: 'Pack',
      size: 'Large',
      price: 158,
      location: 'Tallahassee, FL',
      category: 'supplies',
      listingType: 'fixed',
      lotSize: 4,
      images: [imagePaths.supplies],
      lead: 'NestWorx is a four-pack of nesting boxes built for a tidy coop and easier morning egg collection.',
      details: 'They mount cleanly, are easy to wipe down, and give hens a consistent place to lay.',
      fit: 'A clean upgrade for backyard poultry keepers who want fewer cracked eggs and less coop clutter.',
    },
    {
      title: 'MilkMate - Stainless Pail Set',
      petName: 'MilkMate',
      species: 'Feeding',
      breed: 'Stainless Pail Set',
      age: 'New',
      gender: 'Set',
      size: 'Medium',
      price: 88,
      location: 'Fresno, CA',
      category: 'supplies',
      listingType: 'fixed',
      images: [imagePaths.supplies, imagePaths.livestockAlt],
      lead: 'MilkMate is a stainless pail set for hand milking, cleaning, and keeping dairy chores simple.',
      details: 'The pails rinse quickly, stack neatly, and hold up well under daily farm use.',
      fit: 'A practical buy for goat or cow owners who want durable, washable milking gear.',
    },
    {
      title: 'SunGuard - Shade Cloth Roll',
      petName: 'SunGuard',
      species: 'Housing',
      breed: 'Shade Cloth',
      age: 'New',
      gender: 'Roll',
      size: 'Large',
      price: 112,
      location: 'Las Vegas, NV',
      category: 'supplies',
      listingType: 'fixed',
      images: [imagePaths.supplies],
      lead: 'SunGuard is a heavy shade cloth roll that keeps pens, hutches, and loafing areas cooler.',
      details: 'It cuts cleanly, installs quickly, and helps reduce stress on hot summer days.',
      fit: 'A good add-on for any farm dealing with bright sun and animals that need a little relief.',
    },
    {
      title: 'PawTrace - GPS Collar Bundle',
      petName: 'PawTrace',
      species: 'Tracking',
      breed: 'GPS Collar Bundle',
      age: 'New',
      gender: 'Pack',
      size: 'Small',
      price: 149,
      location: 'Seattle, WA',
      category: 'supplies',
      listingType: 'fixed',
      lotSize: 2,
      images: [imagePaths.supplies, imagePaths.catAlt],
      lead: 'PawTrace is a two-pack of GPS collars that helps keep track of pets, pasture helpers, or escape artists.',
      details: 'The units are lightweight, rechargeable, and made for buyers who like a little extra peace of mind.',
      fit: 'Best for homes with clever animals that like to explore past the fence or porch.',
    },
    {
      title: 'ColostrumVault - Starter Kit',
      petName: 'ColostrumVault',
      species: 'Nutrition',
      breed: 'Newborn Kit',
      age: 'New',
      gender: 'Kit',
      size: 'Small',
      price: 62,
      location: 'Murray, KY',
      category: 'supplies',
      listingType: 'fixed',
      images: [imagePaths.supplies],
      lead: 'ColostrumVault is a starter kit for newborn calves, kids, or lambs that need a stronger first week.',
      details: 'It is simple to store, easy to mix, and geared toward people who keep a few young animals on hand.',
      fit: 'A sensible backup for small farms that want to be ready before a hard delivery day shows up.',
    },
    {
      title: 'HoofHush - Mineral Feeder',
      petName: 'HoofHush',
      species: 'Feeding',
      breed: 'Mineral Feeder',
      age: 'New',
      gender: 'Unit',
      size: 'Medium',
      price: 54,
      location: 'Omaha, NE',
      category: 'supplies',
      listingType: 'fixed',
      images: [imagePaths.supplies],
      lead: 'HoofHush is a weather-resistant mineral feeder that keeps blocks dry and easy for livestock to reach.',
      details: 'It is simple to mount, easy to refill, and helps keep pasture supplements in better shape.',
      fit: 'A useful utility piece for cattle, goat, or sheep pastures that need minerals available year-round.',
    },
    {
      title: 'BroodBright - Heat Plate',
      petName: 'BroodBright',
      species: 'Brooding',
      breed: 'Heat Plate',
      age: 'New',
      gender: 'Unit',
      size: 'Small',
      price: 87,
      location: 'Fayetteville, AR',
      category: 'supplies',
      listingType: 'fixed',
      images: [imagePaths.supplies, imagePaths.birdAlt],
      lead: 'BroodBright is a low-profile heat plate for chicks and ducklings that need steady warmth without a bulb.',
      details: 'It is safer than a hanging lamp for many setups and keeps a smaller brood area calm and warm.',
      fit: 'Best for poultry keepers who want a cleaner, quieter brooding setup.',
    },
    {
      title: 'CoopCart - Feed Tote',
      petName: 'CoopCart',
      species: 'Transport',
      breed: 'Rolling Feed Tote',
      age: 'New',
      gender: 'Unit',
      size: 'Large',
      price: 129,
      location: 'Charlotte, NC',
      category: 'supplies',
      listingType: 'fixed',
      images: [imagePaths.supplies],
      lead: 'CoopCart is a rolling tote for hauling feed, bedding, or daily supplies around a busy property.',
      details: 'The cart is easy to steer, holds a surprising amount, and keeps one trip from turning into five.',
      fit: 'A good choice for sellers and keepers who do a lot of moving between barn, coop, and storage.',
    },
    {
      title: 'DustOff - Livestock Brush Set',
      petName: 'DustOff',
      species: 'Grooming',
      breed: 'Brush Set',
      age: 'New',
      gender: 'Set',
      size: 'Medium',
      price: 44,
      location: 'Asheville, NC',
      category: 'supplies',
      listingType: 'fixed',
      images: [imagePaths.supplies, imagePaths.livestockAlt],
      lead: 'DustOff is a sturdy brush set for cattle, goats, and show animals that need regular coat care.',
      details: 'The brushes clean easily, feel solid in the hand, and are sized for daily barn use.',
      fit: 'A simple but useful kit for anyone polishing up livestock before a show or sale.',
    },
    {
      title: 'PenGuard - Portable Panel Kit',
      petName: 'PenGuard',
      species: 'Housing',
      breed: 'Portable Panel Kit',
      age: 'New',
      gender: 'Kit',
      size: 'Large',
      price: 275,
      location: 'Durango, CO',
      category: 'supplies',
      listingType: 'fixed',
      images: [imagePaths.supplies, imagePaths.livestockAlt],
      lead: 'PenGuard is a portable panel kit that helps create quick pens, sorting lanes, or short-term holds.',
      details: 'The sections are easy to move, lock together cleanly, and make temporary setups a lot less chaotic.',
      fit: 'Best for farms that need flexible space for handling new arrivals or separating animals quickly.',
    },
    {
      title: 'HutchHarbor - Rabbit Starter Kit',
      petName: 'HutchHarbor',
      species: 'Housing',
      breed: 'Rabbit Starter Kit',
      age: 'New',
      gender: 'Kit',
      size: 'Small',
      price: 138,
      location: 'Portland, OR',
      category: 'supplies',
      listingType: 'fixed',
      images: [imagePaths.supplies, imagePaths.rabbitAlt],
      lead: 'HutchHarbor is a rabbit starter kit with the basics for housing, feeding, and easy daily care.',
      details: 'It is aimed at new rabbit owners who want something practical, tidy, and ready to set up fast.',
      fit: 'A strong starter bundle for indoor or sheltered rabbit keeping.',
    },
    {
      title: 'StableSpring - Stall Mat Roll',
      petName: 'StableSpring',
      species: 'Hardware',
      breed: 'Stall Mat Roll',
      age: 'New',
      gender: 'Roll',
      size: 'Large',
      price: 310,
      location: 'Lexington, KY',
      category: 'supplies',
      listingType: 'fixed',
      images: [imagePaths.supplies],
      lead: 'StableSpring is a stall mat roll that softens footing and makes clean-up easier in high-traffic spaces.',
      details: 'It is thick, durable, and built for barns that need better traction and less wear on the floor.',
      fit: 'A useful infrastructure upgrade for horses, cattle, or any barn that sees daily use.',
    },
    {
      title: 'VetVest - First Aid Rollout',
      petName: 'VetVest',
      species: 'Healthcare',
      breed: 'First Aid Rollout',
      age: 'New',
      gender: 'Kit',
      size: 'Medium',
      price: 58,
      location: 'Kansas City, MO',
      category: 'supplies',
      listingType: 'fixed',
      images: [imagePaths.supplies],
      lead: 'VetVest is a first-aid rollout with the basics for cuts, small injuries, and quick barn repairs.',
      details: 'It keeps your supplies organized so you are not hunting for wrap, gauze, or tools in the middle of chores.',
      fit: 'A practical safety purchase for any seller or homestead that wants to stay prepared.',
    },
    {
      title: 'FeedVault - Seal Bin',
      petName: 'FeedVault',
      species: 'Storage',
      breed: 'Seal Bin',
      age: 'New',
      gender: 'Unit',
      size: 'Large',
      price: 146,
      location: 'Madison, WI',
      category: 'supplies',
      listingType: 'fixed',
      images: [imagePaths.supplies],
      lead: 'FeedVault is a sealable feed bin that keeps grain dry, clean, and protected from curious pests.',
      details: 'It opens easily, shuts tightly, and makes bulk feed storage feel much more manageable.',
      fit: 'A solid choice for anyone buying feed in larger quantities and wanting less mess in the barn.',
    },
  ];

  const extraPetItems = [
    {
      userId: sarah.id,
      item: {
        title: 'Willow - Toy Poodle',
        petName: 'Willow',
        species: 'Dog',
        breed: 'Toy Poodle',
        age: '9 Months',
        gender: 'Female',
        size: 'Small',
        price: 1180,
        location: 'Austin, TX',
        category: 'pets',
        listingType: 'fixed',
        vaccinated: true,
        neutered: false,
        lead: 'Willow is a bright Toy Poodle puppy with a tidy coat and a very quick sense for routines.',
        details: 'She is vaccinated, socialized, and already comfortable with brushing, crate time, and gentle leash work.',
        fit: 'A strong choice for someone who wants a compact companion with a sharp mind and low shedding.',
      },
    },
    {
      userId: sarah.id,
      item: {
        title: 'Ranger - Pembroke Welsh Corgi',
        petName: 'Ranger',
        species: 'Dog',
        breed: 'Pembroke Welsh Corgi',
        age: '11 Months',
        gender: 'Male',
        size: 'Small',
        price: 990,
        location: 'Boise, ID',
        category: 'pets',
        listingType: 'fixed',
        vaccinated: true,
        neutered: true,
        lead: 'Ranger is a confident Corgi with a sturdy build, a happy trot, and a strong bond to people.',
        details: 'He is house trained, current on vaccinations, and used to a regular play schedule and short walks.',
        fit: 'Best for a home that wants a small dog with a working-dog brain and a big personality.',
      },
    },
    {
      userId: james.id,
      item: {
        title: 'Mira - Ragdoll',
        petName: 'Mira',
        species: 'Cat',
        breed: 'Ragdoll',
        age: '2 Years',
        gender: 'Female',
        size: 'Medium',
        price: 820,
        location: 'Seattle, WA',
        category: 'pets',
        listingType: 'fixed',
        vaccinated: true,
        neutered: true,
        lead: 'Mira is a plush Ragdoll cat with a relaxed way of settling in and a soft, watchful temperament.',
        details: 'She is litter trained, vaccinated, and comfortable with quiet homes, grooming brushes, and sunny windows.',
        fit: 'A good fit for someone who wants a calm lap cat that settles quickly into a steady routine.',
      },
    },
    {
      userId: james.id,
      item: {
        title: 'Puffin - Maine Coon',
        petName: 'Puffin',
        species: 'Cat',
        breed: 'Maine Coon',
        age: '10 Months',
        gender: 'Male',
        size: 'Large',
        price: 1390,
        location: 'Portland, OR',
        category: 'pets',
        listingType: 'fixed',
        vaccinated: true,
        neutered: false,
        lead: 'Puffin is a fluffy Maine Coon kitten with a broad frame and a playful habit of checking every corner.',
        details: 'He is healthy, vaccinated, and already used to brushing, climbing shelves, and confident handling.',
        fit: 'Best for a family that wants a handsome cat who will grow into a gentle giant.',
      },
    },
    {
      userId: james.id,
      item: {
        title: 'Nori - Holland Lop',
        petName: 'Nori',
        species: 'Rabbit',
        breed: 'Holland Lop',
        age: '8 Months',
        gender: 'Female',
        size: 'Small',
        price: 195,
        location: 'Madison, WI',
        category: 'pets',
        listingType: 'fixed',
        vaccinated: false,
        neutered: false,
        lead: 'Nori is a sweet Holland Lop with soft ears and an easy, quiet hop that settles into a room nicely.',
        details: 'She is handled daily, used to hay and pellets, and doing well with a tidy indoor enclosure.',
        fit: 'A good match for a buyer who wants a calm rabbit and already has the right habitat ready.',
      },
    },
    {
      userId: james.id,
      item: {
        title: 'Biscotti - Lionhead Bunny',
        petName: 'Biscotti',
        species: 'Rabbit',
        breed: 'Lionhead',
        age: '7 Months',
        gender: 'Male',
        size: 'Small',
        price: 210,
        location: 'Reno, NV',
        category: 'pets',
        listingType: 'fixed',
        vaccinated: false,
        neutered: true,
        lead: 'Biscotti is a fluffy Lionhead rabbit with a curious nose and a calm way of settling after playtime.',
        details: 'He is litter box trained, healthy, and used to brushing, floor time, and a quiet routine.',
        fit: 'Best for someone who wants a small companion with a big coat and a gentle personality.',
      },
    },
    {
      userId: maria.id,
      item: {
        title: 'Tango - Parakeet Pair',
        petName: 'Tango',
        species: 'Bird',
        breed: 'Budgerigar Pair',
        age: '8 Months',
        gender: 'Pair',
        size: 'Small',
        price: 160,
        location: 'Tampa, FL',
        category: 'pets',
        listingType: 'fixed',
        lead: 'Tango is a bonded pair of cheerful parakeets with quick movement and a bright, homey chatter.',
        details: 'They are healthy, used to a steady feeding rhythm, and comfortable with a clean cage and daily attention.',
        fit: 'A nice choice for someone who wants small birds that are lively without being complicated.',
      },
    },
    {
      userId: maria.id,
      item: {
        title: 'Junebug - Sun Conure',
        petName: 'Junebug',
        species: 'Bird',
        breed: 'Sun Conure',
        age: '14 Months',
        gender: 'Female',
        size: 'Small',
        price: 940,
        location: 'Orlando, FL',
        category: 'pets',
        listingType: 'fixed',
        vaccinated: false,
        neutered: false,
        lead: 'Junebug is a vivid Sun Conure with bold color, plenty of energy, and a strong bond to people she trusts.',
        details: 'She is hand-friendly, healthy, and accustomed to toys, short training sessions, and a regular light cycle.',
        fit: 'Best for an experienced bird home that can give her time, attention, and a little noise tolerance.',
      },
    },
    {
      userId: maria.id,
      item: {
        title: 'Pebble - Guinea Pig Pair',
        petName: 'Pebble',
        species: 'Guinea Pig',
        breed: 'Peruvian Pair',
        age: '5 Months',
        gender: 'Pair',
        size: 'Small',
        price: 140,
        location: 'Madison, WI',
        category: 'pets',
        listingType: 'fixed',
        lead: 'Pebble is a calm pair of guinea pigs with soft coats and an easy routine around fresh hay and vegetables.',
        details: 'They are healthy, used to gentle handling, and doing well in a tidy indoor enclosure.',
        fit: 'A good option for a family that wants small pets and already has the right habitat set up.',
      },
    },
    {
      userId: maria.id,
      item: {
        title: 'Cinder - Sable Ferret',
        petName: 'Cinder',
        species: 'Ferret',
        breed: 'Sable Ferret',
        age: '1 Year',
        gender: 'Male',
        size: 'Small',
        price: 330,
        location: 'Denver, CO',
        category: 'pets',
        listingType: 'fixed',
        vaccinated: true,
        neutered: true,
        lead: 'Cinder is a curious sable ferret with a playful streak and a strong interest in tunnels and soft blankets.',
        details: 'He is socialized, healthy, and used to a secure enclosure with daily out-of-cage time.',
        fit: 'Best for an experienced small-pet home that understands ferret-proofing and daily play.',
      },
    },
  ];

  const jamesSupplySelection = jamesSupplyItems.slice(0, 3);
  const mariaSupplyItems = jamesSupplyItems.slice(3, 15);

  const allItems = [
    ...[
      ...sarahItems.slice(0, 10),
      ...sarahLivestockItems,
    ].map((item) => ({ item, userId: sarah.id })),
    ...[
      jamesItems[0],
      jamesItems[1],
      jamesItems[2],
      jamesItems[3],
      jamesItems[7],
      jamesItems[8],
      jamesItems[9],
      ...jamesLivestockItems,
      ...jamesSupplySelection,
    ].map((item) => ({ item, userId: james.id })),
    ...[
      ...mariaBirdItems,
      ...mariaItems.slice(0, 5),
      ...mariaSupplyItems,
    ].map((item) => ({ item, userId: maria.id })),
    ...extraLivestockItems.map((item) => ({ item, userId: maria.id })),
    ...extraSupplyItems.map((item) => ({ item, userId: maria.id })),
    ...extraPetItems.map(({ item, userId }) => ({ item, userId })),
  ];

  const listingResults = await Promise.all(
    allItems.map(({ item, userId }, index) => syncListing(item, userId, index))
  );
  const listings = listingResults.map(({ listing }) => listing);
  const createdListings = listingResults.filter(({ action }) => action === 'created').length;
  const updatedListings = listingResults.filter(({ action }) => action === 'updated').length;

  await Promise.all([
    ensureReview({ rating: 5, comment: 'Sarah was organized, warm, and sent exactly the animal we discussed.', reviewerId: james.id, sellerId: sarah.id }),
    ensureReview({ rating: 5, comment: 'James gave clear answers and kept the whole pickup process easy.', reviewerId: maria.id, sellerId: james.id }),
    ensureReview({ rating: 4, comment: 'Maria had clean supplies, solid photos, and practical product notes.', reviewerId: sarah.id, sellerId: maria.id }),
    ensureReview({ rating: 5, comment: 'Great communication and healthy animals that matched the listing photos.', reviewerId: admin.id, sellerId: sarah.id }),
  ]);

  await Promise.all([
    ensureFavorite(james.id, listings[0].id),
    ensureFavorite(maria.id, listings[1].id),
    ensureFavorite(sarah.id, listings[20].id),
    ensureFavorite(admin.id, listings[32].id),
    ensureFavorite(james.id, listings[45].id),
  ]);

  await Promise.all([
    ensureMessage({ content: 'Hi Sarah, I am interested in Sunny. Is he still available?', senderId: james.id, receiverId: sarah.id, listingId: listings[0].id }),
    ensureMessage({ content: 'Yes, Sunny is available and ready for a meeting this weekend.', senderId: sarah.id, receiverId: james.id, listingId: listings[0].id }),
    ensureMessage({ content: "James, can you share a little more about Marlow's routine?", senderId: maria.id, receiverId: james.id, listingId: listings[16].id }),
    ensureMessage({ content: 'Absolutely. He does best with a steady feeding time and a quiet room.', senderId: james.id, receiverId: maria.id, listingId: listings[16].id }),
    ensureMessage({ content: 'Maria, I love the Jersey cow listing. How is Maribel on the halter?', senderId: sarah.id, receiverId: maria.id, listingId: listings[30].id }),
  ]);

  const categoryCounts = allItems.reduce((acc, { item }) => {
    acc[item.category] = (acc[item.category] || 0) + 1;
    return acc;
  }, {});

  const sellerIds = [sarah.id, james.id, maria.id];
  const sellerListingCount = await prisma.listing.count({
    where: { userId: { in: sellerIds } },
  });

  console.log('Catalog sync complete.');
  console.log(`Users ensured: 4 (3 sellers plus admin)`);
  console.log(`Listings synced this run: ${listings.length} (${createdListings} created, ${updatedListings} updated)`);
  console.log(`Seller listings now present: ${sellerListingCount}`);
  console.log(`Mix target: ${categoryCounts.pets || 0} pets, ${categoryCounts.livestock || 0} livestock, ${categoryCounts.supplies || 0} supplies`);
  console.log('Login hint: sarah@example.com, james@example.com, and maria@example.com use password123 after sync.');

  await prisma.$disconnect();
}

seed().catch((error) => {
  console.error(error);
  prisma.$disconnect();
  process.exit(1);
});
